[Appearance]
color_scheme_path=__HOME__/.config/qt6ct/colors/matugen.conf
custom_palette=true
icon_theme=BreezeDarkMonochrome
standard_dialogs=default
style=Fusion

[Fonts]
fixed="JetBrains Mono,10,-1,5,50,0,0,0,0,0"
general="JetBrains Mono,10,-1,5,50,0,0,0,0,0"

[Interface]
dialog_buttons_have_icons=1
