local home = os.getenv("HOME") or "/home/" .. (os.getenv("USER") or "user")
package.path = package.path .. ";" .. home .. "/.config/hypr/?.lua;" .. home .. "/.config/hypr/?/init.lua"
-- Hyprland configuration — Clean & Polished
-- https://wiki.hypr.land/Configuring/Start/

hl.config({ autogenerated = false })

-- ========================================
-- ENVIRONMENT VARIABLES
-- ========================================
-- GPU selection is made by start-hyprland-clean before Hyprland starts.
-- Wayland
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
-- Cursor
hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("HYPRCURSOR_SIZE", "24")
-- Qt / Electron
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
hl.env("QT_QPA_PLATFORMTHEME_QT6", "qt6ct")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_ENABLE_HIGHDPI_SCALING", "1")
-- GTK_THEME removed: it overrides libadwaita apps; settings.ini + gsettings already set Breeze-Dark
-- hl.env("GTK_THEME", "Breeze-Dark")
hl.env("COLORSCHEME", "prefer-dark")
hl.env("NO_PROXY", "127.0.0.1,localhost,::1")
hl.env("no_proxy", "127.0.0.1,localhost,::1")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("MOZ_ENABLE_WAYLAND", "1")
-- Terminal
hl.env("TERMINAL", "kitty")

-- ========================================
-- AUTOSTART
-- ========================================
hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE HYPRLAND_INSTANCE_SIGNATURE DISPLAY &")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE HYPRLAND_INSTANCE_SIGNATURE DISPLAY &")
    hl.exec_cmd("hyprpaper &")
    -- The palette is already cached. Avoid regenerating it on every login;
    -- DMS' Matugen worker otherwise delays the completed shell by ~4 seconds.
    hl.exec_cmd("env DMS_DISABLE_MATUGEN=1 dms run &")
    hl.exec_cmd("wl-clip-persist --clipboard regular &")
end)

-- ========================================
-- INPUT
-- ========================================
hl.device({
    name = "elan06fa:00-04f3:327e-touchpad",
    accel_profile = "adaptive",
    sensitivity = 0.0,
    disable_while_typing = true,
    tap_to_click = false,
    clickfinger_behavior = false,
})

hl.device({
    name = "elan06fa:00-04f3:327e-mouse",
    disable_while_typing = true,
    tap_to_click = false,
})

hl.config({
    input = {
        kb_layout = "us",
        repeat_rate = 50,
        repeat_delay = 280,
        numlock_by_default = true,
        follow_mouse = 1,        -- focus follows mouse
        sensitivity = -0.8,
        accel_profile = "flat",  -- no acceleration
        touchpad = {
            tap_to_click = false,
            natural_scroll = true,
            scroll_factor = 0.3,
            disable_while_typing = true,
            clickfinger_behavior = false,
            middle_button_emulation = false,
        },
    },
})

-- ========================================
-- GENERAL
-- ========================================
hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 10,
        border_size = 0,
        layout = "dwindle",
        resize_on_border = true,
        allow_tearing = true,
        ["col.active_border"] = "rgba(d9d9d9a0)",
        ["col.inactive_border"] = "rgba(33333318)",
    },
})

-- ========================================
-- DECORATION
-- ========================================
hl.config({
    decoration = {
        rounding = 7,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        blur = {
            enabled = true,
            size = 2,
            passes = 1,
            new_optimizations = true,
            xray = false,
            vibrancy = 0.03,
            noise = 0,
        },
        shadow = {
            enabled = true,
            range = 16,
            render_power = 2,
            color = "rgba(aaaaaa09)",
        },
    },
})

hl.config({
    animations = {
        enabled = true,
    },
})

-- Safe universal monitor fallback (ensures desktop never black-screens on unknown monitors)
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })

-- Multi-monitor profile (mixed-refresh laptop + HDMI panel)
hl.monitor({ output = "eDP-1", mode = "1920x1080@144", position = "0x0", scale = 1, vrr = 1 })
hl.monitor({ output = "HDMI-A-1", mode = "highrr", position = "1920x0", scale = 1, vrr = 0 })

-- Machine-local monitor override (if present, ignored by git)
pcall(require, "monitors.local")

-- Smooth curve for window movement and maximize/fullscreen transitions (Super + F)
hl.curve("smoothOut", { type = "bezier", points = { { 0.16, 1.0 }, { 0.3, 1.0 } } })

-- Harmonized animation set (workspaces/layers/popins at speed 4; fullscreen/movement on smoothOut)
hl.animation({ leaf = "global",           enabled = true, speed = 4,   bezier = "default" })
hl.animation({ leaf = "workspaces",       enabled = true, speed = 4,   bezier = "default" })
hl.animation({ leaf = "specialWorkspace",  enabled = true, speed = 4,   bezier = "default", style = "slidevert" })
hl.animation({ leaf = "windowsIn",        enabled = true, speed = 4,   bezier = "default", style = "popin 80%" })
hl.animation({ leaf = "windowsOut",       enabled = true, speed = 4,   bezier = "default", style = "popin 80%" })
hl.animation({ leaf = "windowsMove",      enabled = true, speed = 5.5, bezier = "smoothOut" })
hl.animation({ leaf = "fade",             enabled = true, speed = 4,   bezier = "default" })
hl.animation({ leaf = "fadeIn",           enabled = true, speed = 4,   bezier = "default" })
hl.animation({ leaf = "fadeOut",          enabled = true, speed = 4,   bezier = "default" })
hl.animation({ leaf = "layers",           enabled = true, speed = 4,   bezier = "default" })
hl.animation({ leaf = "layersIn",         enabled = true, speed = 4,   bezier = "default", style = "popin 80%" })
hl.animation({ leaf = "layersOut",        enabled = true, speed = 4,   bezier = "default", style = "popin 80%" })
hl.animation({ leaf = "border",           enabled = true, speed = 4,   bezier = "default" })
-- Borders are disabled below; do not keep an invisible animation running every frame.
hl.animation({ leaf = "borderangle",      enabled = false, speed = 100, bezier = "linear",  style = "loop" })

-- ========================================
-- DWINDLE TILING (vanilla)
-- ========================================
hl.config({
    dwindle = {
        preserve_split = false,
    },
})

-- ========================================
-- MISC
-- ========================================
hl.config({
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        background_color = "0x000000",
        mouse_move_enables_dpms = true,
        key_press_enables_dpms = true,
        animate_manual_resizes = false,
        vrr = 1,
    },
})

-- Let Hyprland use triple buffering only when presentation timing needs it.
-- This is useful on mixed-refresh setups without forcing extra latency all the time.
hl.config({
    render = {
        new_render_scheduling = true,
        -- Automatically bypass the compositor for compatible fullscreen games.
        direct_scanout = 2,
    },
})

-- ========================================
-- XWAYLAND (crisp rendering)
-- ========================================
hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

-- ========================================
-- WORKSPACE STARTING LAYOUT
-- ========================================
-- If a multi-monitor setup with HDMI-A-1 is connected, pin workspace 1 to HDMI and 2 to eDP.
-- Otherwise, workspaces stay dynamically attached to whichever monitor is available.
local function is_monitor_connected(name)
    local f = io.open("/sys/class/drm/card1-" .. name .. "/status", "r")
        or io.open("/sys/class/drm/card0-" .. name .. "/status", "r")
        or io.open("/sys/class/drm/card2-" .. name .. "/status", "r")
    if f then
        local status = f:read("*l")
        f:close()
        return status == "connected"
    end
    return false
end

if is_monitor_connected("HDMI-A-1") and is_monitor_connected("eDP-1") then
    hl.workspace_rule({ workspace = "1", monitor = "HDMI-A-1", default = true, persistent = true })
    hl.workspace_rule({ workspace = "2", monitor = "eDP-1", default = true, persistent = true })
end

-- ========================================
-- WINDOW RULES
-- ========================================

-- Polkit Authentication Dialogs
hl.window_rule({
    match = { class = "^(polkit-gnome-authentication-agent-1|io\\.elementary\\.desktop\\.agent-polkit|hyprpolkitagent|org\\.freedesktop\\.impl\\.portal\\.desktop\\.gtk)$" },
    float = true,
    pin = true,
    center = true,
})

-- Suppress animation on DMS overlay
hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })
hl.layer_rule({ match = { namespace = "^dms:.*" }, no_anim = true })
hl.layer_rule({ match = { namespace = "^(selection|hyprpicker)$" }, no_anim = true })

-- ========================================
-- DMS MODULES (always last)
-- ========================================
package.loaded["dms.colors"]      = nil
package.loaded["dms.outputs"]     = nil
package.loaded["dms.layout"]      = nil
package.loaded["dms.cursor"]      = nil
package.loaded["dms.binds"]       = nil
package.loaded["dms.binds-user"]  = nil
package.loaded["dms.windowrules"] = nil

require("dms.colors")
require("dms.outputs")
require("dms.layout")
require("dms.cursor")

-- Keep the chosen cursor authoritative if DMS regenerates dms/cursor.lua.
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_SIZE", "24")
require("dms.binds")
require("dms.binds-user")

hl.bind("CTRL + ALT + Q", hl.dsp.exec_cmd("/usr/bin/python3 " .. home .. "/.local/bin/toggle-display-refresh"), { description = "Toggle laptop refresh rate (60 / 144 Hz)" })
require("dms.windowrules")

-- ========================================
-- CUSTOM DESIGN OVERRIDES
-- ========================================
hl.config({
    general = {
        border_size = 0,
        resize_on_border = true,
        allow_tearing = true,
        ["col.active_border"] = "rgba(d9d9d9a0)",
        ["col.inactive_border"] = "rgba(33333318)",
    },
    cursor = {
        default_monitor = "",
    },
    decoration = {
        rounding = 7,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        blur = {
            enabled = true,
            size = 2,
            passes = 1,
            new_optimizations = true,
            xray = false,
            vibrancy = 0.03,
            noise = 0,
        },
        shadow = {
            enabled = true,
            range = 16,
            render_power = 2,
            color = "rgba(aaaaaa09)",
        },
    },
    windowrulev2 = {
        "opacity 0.90 0.90, class:^(kitty|spoff)$",
        "noblur, class:^(kitty|spoff)$",
        "noblur, class:^(nvim)$",
        "opaque, class:^(Antigravity|antigravity)$",
        "immediate, class:^(minecraft|Minecraft.*|lunarclient|Lunar Client.*|prismlauncher|steam_app_.*|cs2)$",
    }
})

-- HyprMod managed settings
pcall(require, "hyprland-gui")
