preload = /home/vrdq/dotfiles/wallpapers/Arch_Linux_OG_Flat_Solid_131313_4K.png
wallpaper = eDP-1,/home/vrdq/dotfiles/wallpapers/Arch_Linux_OG_Flat_Solid_131313_4K.png
wallpaper = HDMI-A-1,/home/vrdq/dotfiles/wallpapers/Arch_Linux_OG_Flat_Solid_131313_4K.png
splash = false
