package.path = package.path .. ";/home/vrdq/.config/hypr/?.lua;/home/vrdq/.config/hypr/?/init.lua"
-- Hyprland configuration — Clean & Polished
-- https://wiki.hypr.land/Configuring/Start/

hl.config({ autogenerated = false })

-- ========================================
-- ENVIRONMENT VARIABLES
-- ========================================
-- NVIDIA
hl.env("AQ_DRM_DEVICES", "/dev/dri/card1")
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
-- hl.env("GBM_BACKEND", "nvidia-drm")
hl.env("__GL_GSYNC_ALLOWED", "1")
hl.env("__GL_VRR_ALLOWED", "1")
hl.env("NVD_BACKEND", "direct")
hl.env("AQ_NO_MODIFIERS", "1")
-- NVIDIA documents these as lower-wait / multithreaded OpenGL paths. They
-- trade a little CPU time for steadier compositor submission at high refresh.
hl.env("__GL_YIELD", "NOTHING")
hl.env("__GL_THREADED_OPTIMIZATIONS", "1")
hl.env("__GL_SYNC_DISPLAY_DEVICE", "eDP-1")
-- Wayland
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
-- Cursor
hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("XCURSOR_SIZE", "20")
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("HYPRCURSOR_SIZE", "20")
-- Qt / Electron
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_QPA_PLATFORMTHEME", "kde")
hl.env("QT_QPA_PLATFORMTHEME_QT6", "kde")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_ENABLE_HIGHDPI_SCALING", "1")
hl.env("GTK_THEME", "Breeze-Dark")
hl.env("COLORSCHEME", "prefer-dark")
hl.env("NO_PROXY", "127.0.0.1,localhost,::1")
hl.env("no_proxy", "127.0.0.1,localhost,::1")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("QSG_RENDER_LOOP", "threaded")
hl.env("MOZ_ENABLE_WAYLAND", "1")
-- Terminal
hl.env("TERMINAL", "kitty")

-- ========================================
-- AUTOSTART
-- ========================================
hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE HYPRLAND_INSTANCE_SIGNATURE DISPLAY &")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE HYPRLAND_INSTANCE_SIGNATURE DISPLAY &")
    hl.exec_cmd("xrandr --output eDP-1 --primary &")
    hl.exec_cmd("hyprpaper &")
    -- The palette is already cached. Avoid regenerating it on every login;
    -- DMS' Matugen worker otherwise delays the completed shell by ~4 seconds.
    hl.exec_cmd("env DMS_DISABLE_MATUGEN=1 dms run &")
end)

-- ========================================
-- INPUT
-- ========================================
hl.device({
    name = "elan06fa:00-04f3:327e-touchpad",
    accel_profile = "adaptive",
    sensitivity = 0.0,
    disable_while_typing = true,
    tap_to_click = false,
    clickfinger_behavior = false,
})

hl.device({
    name = "elan06fa:00-04f3:327e-mouse",
    disable_while_typing = true,
    tap_to_click = false,
})

hl.config({
    input = {
        kb_layout = "us",
        repeat_rate = 50,
        repeat_delay = 280,
        numlock_by_default = true,
        follow_mouse = 1,        -- focus follows mouse
        sensitivity = -0.8,
        accel_profile = "flat",  -- no acceleration
        touchpad = {
            tap_to_click = false,
            natural_scroll = true,
            scroll_factor = 0.3,
            disable_while_typing = true,
            clickfinger_behavior = false,
            middle_button_emulation = false,
        },
    },
})

-- ========================================
-- GENERAL
-- ========================================
hl.config({
    general = {
        gaps_in = 4,
        gaps_out = 8,
        border_size = 0,
        layout = "dwindle",
        resize_on_border = true,
        allow_tearing = true,
        ["col.active_border"] = "rgba(ffffffff)",
        ["col.inactive_border"] = "rgba(333333aa)",
    },
})

-- ========================================
-- DECORATION
-- ========================================
hl.config({
    decoration = {
        rounding = 10,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        blur = {
            enabled = true,
            size = 3,
            passes = 2,
            new_optimizations = true,
            xray = false,
            vibrancy = 0.05,
            noise = 0,
        },
        shadow = {
            enabled = true,
            range = 20,
            render_power = 3,
            color = "rgba(aaaaaa0e)",
        },
    },
})

hl.config({
    animations = {
        enabled = true,
    },
})

-- Ultra-smooth 144Hz animation curves (zero bounce, pure fluid deceleration)
hl.bezier({ name = "fluid144",   c1 = 0.16, c2 = 1.0, c3 = 0.3, c4 = 1.0 })

hl.animation({ leaf = "global",      enabled = true, speed = 3.5, bezier = "fluid144" })
hl.animation({ leaf = "windowsIn",   enabled = true, speed = 3.5, bezier = "fluid144", style = "popin 80%" })
hl.animation({ leaf = "windowsOut",  enabled = true, speed = 3.5, bezier = "fluid144", style = "popin 80%" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 3.5, bezier = "fluid144" })
hl.animation({ leaf = "fade",        enabled = true, speed = 3.5, bezier = "fluid144" })
hl.animation({ leaf = "border",      enabled = true, speed = 3.5, bezier = "fluid144" })
-- Borders are disabled below; do not keep an invisible animation running every frame.
hl.animation({ leaf = "borderangle", enabled = false, speed = 100, bezier = "linear", style = "loop" })
hl.animation({ leaf = "workspaces",  enabled = true, speed = 3.5, bezier = "fluid144", style = "slide" })
hl.animation({ leaf = "layers",      enabled = true, speed = 3.5, bezier = "fluid144" })

-- ========================================
-- DEBUG & FULL-FRAME REFRESH PACING
-- ========================================
hl.config({
    debug = {
        damage_tracking = 0,
    },
})

-- ========================================
-- DWINDLE TILING (vanilla)
-- ========================================
hl.config({
    dwindle = {
        preserve_split = false,
    },
})

-- ========================================
-- MISC
-- ========================================
hl.config({
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        background_color = "0x000000",
        mouse_move_enables_dpms = true,
        key_press_enables_dpms = true,
        animate_manual_resizes = false,
        vrr = 0,
    },
})

-- ========================================
-- XWAYLAND (crisp rendering)
-- ========================================
hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

-- ========================================
-- PERSISTENT WORKSPACE SLOTS
-- Keeps empty workspaces visible/available; it does not pre-render framebuffers.
-- ========================================
hl.workspace_rule({ workspace = "1", persistent = true })
hl.workspace_rule({ workspace = "2", persistent = true })
hl.workspace_rule({ workspace = "3", persistent = true })
hl.workspace_rule({ workspace = "4", persistent = true })
hl.workspace_rule({ workspace = "5", persistent = true })

-- ========================================
-- WINDOW RULES
-- ========================================

-- Polkit Authentication Dialogs
hl.window_rule({
    match = { class = "^(polkit-gnome-authentication-agent-1|io\\.elementary\\.desktop\\.agent-polkit|hyprpolkitagent|org\\.freedesktop\\.impl\\.portal\\.desktop\\.gtk)$" },
    float = true,
    pin = true,
    center = true,
})

-- Float small/utility windows
hl.window_rule({ match = { class = "^(org\\.gnome\\.Calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(gnome-calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(galculator)$" }, float = true })
hl.window_rule({ match = { class = "^(blueman-manager)$" }, float = true, size = "700 450" })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Nautilus)$" }, float = true, size = "900 600" })
hl.window_rule({ match = { class = "^(xdg-desktop-portal)$" }, float = true })
hl.window_rule({ match = { class = "^(pavucontrol)$" }, float = true, size = "800 500" })
hl.window_rule({ match = { class = "^(nm-connection-editor)$" }, float = true })
hl.window_rule({ match = { class = "^(zoom)$" }, float = true })

-- Keep big apps tiled
hl.window_rule({ match = { class = "^(spotify)$" }, tile = true })
hl.window_rule({ match = { class = "^(vesktop)$" }, tile = true })
hl.window_rule({ match = { class = "^(discord)$" }, tile = true })
hl.window_rule({ match = { class = "^(librewolf)$" }, tile = true })

-- Steam
hl.window_rule({
    match = { class = "^(steam)$", title = "^(notificationtoasts)" },
    no_initial_focus = true,
    pin = true,
})

-- Firefox / LibreWolf Picture-in-Picture
hl.window_rule({
    match = { class = "^(firefox|librewolf)$", title = "^(Picture-in-Picture)$" },
    float = true,
    pin = true,
})

-- Suppress animation on DMS overlay
hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })
hl.layer_rule({ match = { namespace = "^dms:.*" }, no_anim = true })

-- ========================================
-- DMS MODULES (always last)
-- ========================================
package.loaded["dms.colors"]      = nil
package.loaded["dms.outputs"]     = nil
package.loaded["dms.layout"]      = nil
package.loaded["dms.cursor"]      = nil
package.loaded["dms.binds"]       = nil
package.loaded["dms.binds-user"]  = nil
package.loaded["dms.windowrules"] = nil

require("dms.colors")
require("dms.outputs")
require("dms.layout")
require("dms.cursor")

-- Keep the chosen cursor authoritative if DMS regenerates dms/cursor.lua.
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("HYPRCURSOR_SIZE", "20")
hl.env("XCURSOR_SIZE", "20")
require("dms.binds")
require("dms.binds-user")
require("dms.windowrules")

-- ========================================
-- CUSTOM DESIGN OVERRIDES
-- ========================================
hl.config({
    general = {
        border_size = 0,
        ["col.active_border"] = "rgba(ffffffff)",
        ["col.inactive_border"] = "rgba(333333aa)",
    },
    cursor = {
        default_monitor = "eDP-1",
    },
    decoration = {
        rounding = 10,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        blur = {
            enabled = true,
            size = 3,
            passes = 2,
            new_optimizations = true,
            xray = false,
            vibrancy = 0.05,
            noise = 0,
        },
        shadow = {
            enabled = true,
            range = 20,
            render_power = 3,
            color = "rgba(aaaaaa0e)",
        },
    },
    windowrulev2 = {
        "opacity 0.85 0.85, class:^(kitty)$",
        "noblur, class:^(kitty)$",
        "noblur, class:^(nvim)$",
        "tile, class:^(Antigravity|antigravity)$",
        "opaque, class:^(Antigravity|antigravity)$",
    }
})

hl.config({
    render = {
        direct_scanout = 1,
    },
})

-- ========================================
-- SYSTEM-WIDE SCREEN TEARING & ZERO-LATENCY DIRECT PRESENTATION
-- ========================================
hl.window_rule({ match = { class = ".*" }, immediate = true })
hl.window_rule({ match = { class = "^(Minecraft.*|minecraft.*|net-minecraft-launcher|org\\.prismlauncher\\.PrismLauncher|lunarclient|steam_app_.*|cs2|hl2|gamescope)$" }, immediate = true, no_anim = true, idle_inhibit = "focus" })
