# =============================================================================
# xdg-desktop-portal-hyprland configuration
# =============================================================================

screencopy {
    custom_picker_binary = /home/vrdq/.local/bin/quickshell-share-picker
}
