[Icon Theme]
Name=BreezeDarkMonochrome
Comment=Breeze-Dark with monochrome folder icons
Inherits=breeze-dark
Directories=places/16,places/22,places/24,places/32,places/48,places/64,places/96,places/16@2x,places/16@3x,places/22@2x,places/22@3x,places/24@2x,places/24@3x,mimetypes/16,mimetypes/22,mimetypes/24,mimetypes/32,mimetypes/48,mimetypes/64,mimetypes/96,mimetypes/16@2x,mimetypes/16@3x,mimetypes/22@2x,mimetypes/22@3x,mimetypes/24@2x,mimetypes/24@3x

[places/16]
Size=16
Type=Scalable
MinSize=16
MaxSize=16
Context=Places

[places/22]
Size=22
Type=Scalable
MinSize=22
MaxSize=22
Context=Places

[places/24]
Size=24
Type=Scalable
MinSize=24
MaxSize=24
Context=Places

[places/32]
Size=32
Type=Scalable
MinSize=32
MaxSize=32
Context=Places

[places/48]
Size=48
Type=Scalable
MinSize=48
MaxSize=48
Context=Places

[places/64]
Size=64
Type=Scalable
MinSize=64
MaxSize=64
Context=Places

[places/96]
Size=96
Type=Scalable
MinSize=96
MaxSize=96
Context=Places

[places/16@2x]
Size=16
Scale=2
Type=Scalable
MinSize=16
MaxSize=16
Context=Places

[places/16@3x]
Size=16
Scale=3
Type=Scalable
MinSize=16
MaxSize=16
Context=Places

[places/22@2x]
Size=22
Scale=2
Type=Scalable
MinSize=22
MaxSize=22
Context=Places

[places/22@3x]
Size=22
Scale=3
Type=Scalable
MinSize=22
MaxSize=22
Context=Places

[places/24@2x]
Size=24
Scale=2
Type=Scalable
MinSize=24
MaxSize=24
Context=Places

[places/24@3x]
Size=24
Scale=3
Type=Scalable
MinSize=24
MaxSize=24
Context=Places

[mimetypes/16]
Size=16
Type=Scalable
MinSize=16
MaxSize=16
Context=MimeTypes

[mimetypes/22]
Size=22
Type=Scalable
MinSize=22
MaxSize=22
Context=MimeTypes

[mimetypes/24]
Size=24
Type=Scalable
MinSize=24
MaxSize=24
Context=MimeTypes

[mimetypes/32]
Size=32
Type=Scalable
MinSize=32
MaxSize=32
Context=MimeTypes

[mimetypes/48]
Size=48
Type=Scalable
MinSize=48
MaxSize=48
Context=MimeTypes

[mimetypes/64]
Size=64
Type=Scalable
MinSize=64
MaxSize=64
Context=MimeTypes

[mimetypes/96]
Size=96
Type=Scalable
MinSize=96
MaxSize=96
Context=MimeTypes

[mimetypes/16@2x]
Size=16
Scale=2
Type=Scalable
MinSize=16
MaxSize=16
Context=MimeTypes

[mimetypes/16@3x]
Size=16
Scale=3
Type=Scalable
MinSize=16
MaxSize=16
Context=MimeTypes

[mimetypes/22@2x]
Size=22
Scale=2
Type=Scalable
MinSize=22
MaxSize=22
Context=MimeTypes

[mimetypes/22@3x]
Size=22
Scale=3
Type=Scalable
MinSize=22
MaxSize=22
Context=MimeTypes

[mimetypes/24@2x]
Size=24
Scale=2
Type=Scalable
MinSize=24
MaxSize=24
Context=MimeTypes

[mimetypes/24@3x]
Size=24
Scale=3
Type=Scalable
MinSize=24
MaxSize=24
Context=MimeTypes
