# Oxocarbon btop theme
# Designed to match the dark Oxocarbon and Dank monochrome system aesthetic

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#131313"

# Main text color
theme[main_fg]="#e2e2e2"

# Title color for boxes
theme[title]="#ffffff"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#9bff7f"

# Background color of selected item in processes box
theme[selected_bg]="#262626"

# Foreground color of selected item in processes box
theme[selected_fg]="#ffffff"

# Color of inactive/disabled text
theme[inactive_fg]="#525252"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#78a9ff"

# Cpu box outline color
theme[cpu_box]="#393939"

# Memory/disks box outline color
theme[mem_box]="#393939"

# Net up/down box outline color
theme[net_box]="#393939"

# Processes box outline color
theme[proc_box]="#393939"

# Box divider line and small boxes line color
theme[div_line]="#262626"

# Temperature graph colors
theme[temp_start]="#78a9ff"
theme[temp_mid]="#ffcf87"
theme[temp_end]="#ff5252"

# CPU graph colors
theme[cpu_start]="#525252"
theme[cpu_mid]="#78a9ff"
theme[cpu_end]="#9bff7f"

# Mem/Disk free meter
theme[free_start]="#393939"
theme[free_mid]="#78a9ff"
theme[free_end]="#9bff7f"

# Mem/Disk cached meter
theme[cached_start]="#262626"
theme[cached_mid]="#525252"
theme[cached_end]="#78a9ff"

# Mem/Disk available meter
theme[available_start]="#393939"
theme[available_mid]="#78a9ff"
theme[available_end]="#9bff7f"

# Mem/Disk used meter
theme[used_start]="#525252"
theme[used_mid]="#78a9ff"
theme[used_end]="#ff7272"

# Download graph colors
theme[download_start]="#393939"
theme[download_mid]="#78a9ff"
theme[download_end]="#9bff7f"

# Upload graph colors
theme[upload_start]="#393939"
theme[upload_mid]="#be95ff"
theme[upload_end]="#3ddbd9"
