-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("SUPER + C")
hl.bind("SUPER + C", hl.dsp.exec_cmd("dms ipc call clipboard toggle"), { description = "dms ipc call clipboard toggle" })
hl.unbind("SUPER + L")
hl.bind("SUPER + L", hl.dsp.exec_cmd("dms ipc call lock lock"))
hl.unbind("SUPER + SUPER_L")
hl.bind("SUPER + SUPER_L", hl.dsp.exec_cmd("dms ipc call spotlight toggle"))
hl.unbind("SUPER + 1")
hl.bind("SUPER + 1", hl.dsp.focus({ workspace = "1" }), { description = "Focus workspace 1" })
hl.unbind("SUPER + SHIFT + mouse_down")
hl.bind("SUPER + SHIFT + mouse_down", hl.dsp.window.move({ workspace = "e+1" }))
hl.unbind("SUPER + SHIFT + mouse_up")
hl.bind("SUPER + SHIFT + mouse_up", hl.dsp.window.move({ workspace = "e-1" }))
hl.unbind("SUPER + W")
hl.bind("SUPER + W", hl.dsp.window.move({ workspace = "special:minimized", follow = false }))
hl.unbind("SUPER + right")
hl.bind("SUPER + right", hl.dsp.focus({ workspace = "e+1" }), { description = "Focus next open workspace" })
hl.unbind("Print")
hl.bind("Print", hl.dsp.exec_cmd("/home/vrdq/.local/bin/take-screenshot.sh"))
hl.unbind("SUPER + A")
hl.bind("SUPER + A", hl.dsp.exec_cmd("/home/vrdq/.local/bin/hypr-unminimize.sh"))
hl.unbind("SUPER + Backspace")
hl.bind("SUPER + Backspace", hl.dsp.exec_cmd("/home/vrdq/.local/bin/delete-gap-and-shift.sh"), { description = "Delete gap workspace and shift" })
hl.unbind("SUPER + D")
hl.bind("SUPER + D", hl.dsp.exec_cmd("vesktop"))
hl.unbind("SUPER + E")
hl.bind("SUPER + E", hl.dsp.exec_cmd("dolphin"))
hl.unbind("SUPER + G")
hl.bind("SUPER + G", hl.dsp.exec_cmd("/usr/bin/antigravity"))
hl.unbind("SUPER + R")
hl.bind("SUPER + R", hl.dsp.exec_cmd("librewolf"))
hl.unbind("SUPER + S")
hl.bind("SUPER + S", hl.dsp.exec_cmd("spotify --password-store=basic"))
hl.unbind("SUPER + TAB")
hl.bind("SUPER + TAB", hl.dsp.exec_cmd("/home/vrdq/.local/bin/hypr-show-desktop.sh"), { description = "Show Desktop" })
hl.unbind("ALT + F3")
hl.bind("ALT + F3", hl.dsp.window.close(), { description = "Close window" })
hl.unbind("ALT + F4")
hl.bind("ALT + F4", hl.dsp.window.close())
hl.unbind("ALT + Print")
hl.unbind("ALT + SHIFT + TAB")
hl.unbind("ALT + TAB")
hl.unbind("ALT + space")
hl.unbind("CTRL + Print")
hl.unbind("CTRL + SHIFT + R")
hl.unbind("Escape")
hl.unbind("F11")
hl.bind("F11", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }), { description = "Toggle Fullscreen" })
hl.unbind("F23")
hl.unbind("F24")
hl.unbind("S")
hl.unbind("SUPER + ALT + P")
hl.bind("SUPER + ALT + P", hl.dsp.window.pin())
hl.unbind("SUPER + I")
hl.unbind("SUPER + N")
hl.unbind("SUPER + O")
hl.unbind("SUPER + Page_Down")
hl.unbind("SUPER + Page_Up")
hl.unbind("SUPER + Q")
hl.bind("SUPER + Q", hl.dsp.exec_cmd("kitty"))
hl.unbind("SUPER + SHIFT + F23")
hl.unbind("SUPER + T")
hl.unbind("SUPER + U")
hl.unbind("SUPER + V")
hl.unbind("SUPER + comma")
hl.unbind("SUPER + space")
hl.unbind("XF86Assistant")
hl.unbind("code:248")
