-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)
local home = os.getenv("HOME") or "/home/" .. (os.getenv("USER") or "user")

hl.unbind("SUPER + C")
hl.bind("SUPER + C", hl.dsp.exec_cmd("dms ipc call clipboard toggle"), { description = "dms ipc call clipboard toggle" })
hl.unbind("SUPER + L")
hl.bind("SUPER + L", hl.dsp.exec_cmd("dms ipc call lock lock"))
hl.unbind("SUPER + SUPER_L")
hl.bind("SUPER + SUPER_L", hl.dsp.exec_cmd("dms ipc call spotlight toggle"))
hl.unbind("SUPER + 1")
hl.bind("SUPER + 1", hl.dsp.focus({ workspace = "1" }), { description = "Focus workspace 1" })
hl.unbind("SUPER + W")
hl.bind("SUPER + W", hl.dsp.window.move({ workspace = "special:minimized", follow = false }))
hl.unbind("SUPER + down")
hl.bind("SUPER + down", hl.dsp.window.move({ direction = "d" }), { description = "Swap window down" })
hl.unbind("SUPER + left")
hl.bind("SUPER + left", hl.dsp.window.move({ direction = "l" }), { description = "Swap window left" })
hl.unbind("SUPER + right")
hl.bind("SUPER + right", hl.dsp.window.move({ direction = "r" }), { description = "Swap window right" })
hl.unbind("SUPER + up")
hl.bind("SUPER + up", hl.dsp.window.move({ direction = "u" }), { description = "Swap window up" })
hl.unbind("CTRL + Q")
hl.bind("CTRL + Q", hl.dsp.exec_cmd(home .. "/.local/bin/toggle-power-profile.sh"), { description = "Toggle Power Profile (Balanced / Performance)" })
hl.unbind("Print")
hl.bind("Print", hl.dsp.exec_cmd(home .. "/.local/bin/take-screenshot.sh"))
hl.unbind("SUPER + A")
hl.bind("SUPER + A", hl.dsp.exec_cmd(home .. "/.local/bin/hypr-unminimize.sh"))
hl.unbind("SUPER + D")
hl.bind("SUPER + D", hl.dsp.exec_cmd("vesktop"))
hl.unbind("SUPER + E")
hl.bind("SUPER + E", hl.dsp.exec_cmd("dolphin"))
hl.unbind("SUPER + G")
hl.bind("SUPER + G", hl.dsp.exec_cmd("/usr/bin/antigravity"))
hl.unbind("SUPER + N")
hl.bind("SUPER + N", hl.dsp.exec_cmd("/usr/bin/kitty --class nvim --title Neovim /usr/bin/nvim"), { description = "Open Neovim" })
hl.unbind("SUPER + P")
hl.bind("SUPER + P", hl.dsp.exec_cmd("prismlauncher"), { description = "Launch Prism Launcher" })
hl.unbind("SUPER + Q")
hl.bind("SUPER + Q", hl.dsp.exec_cmd("kitty"))
hl.unbind("SUPER + R")
hl.bind("SUPER + R", hl.dsp.exec_cmd("librewolf"))
hl.unbind("SUPER + TAB")
hl.bind("SUPER + TAB", hl.dsp.exec_cmd(home .. "/.local/bin/hypr-show-desktop.sh"), { description = "Show Desktop" })
hl.unbind("ALT + F3")
hl.bind("ALT + F3", hl.dsp.window.close(), { description = "Close window" })
hl.unbind("ALT + F4")
hl.bind("ALT + F4", hl.dsp.window.close())
hl.unbind("ALT + Print")
hl.unbind("ALT + space")
hl.unbind("CTRL + ALT + Delete")
hl.unbind("CTRL + Print")
hl.unbind("CTRL + SHIFT + R")
hl.unbind("F11")
hl.bind("F11", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }), { description = "Toggle Fullscreen" })
hl.unbind("SUPER + ALT + L")
hl.unbind("SUPER + ALT + P")
hl.bind("SUPER + ALT + P", hl.dsp.window.pin())
hl.unbind("SUPER + CTRL + F")
hl.unbind("SUPER + CTRL + H")
hl.unbind("SUPER + CTRL + I")
hl.unbind("SUPER + CTRL + J")
hl.unbind("SUPER + CTRL + K")
hl.unbind("SUPER + CTRL + L")
hl.unbind("SUPER + CTRL + U")
hl.unbind("SUPER + CTRL + mouse_down")
hl.unbind("SUPER + CTRL + mouse_up")
hl.unbind("SUPER + CTRL + down")
hl.unbind("SUPER + CTRL + left")
hl.unbind("SUPER + CTRL + right")
hl.unbind("SUPER + CTRL + up")
hl.unbind("SUPER + End")
hl.unbind("SUPER + Home")
hl.unbind("SUPER + I")
hl.unbind("SUPER + O")
hl.unbind("SUPER + Page_Down")
hl.unbind("SUPER + Page_Up")
hl.unbind("SUPER + S")
hl.bind("SUPER + S", hl.dsp.exec_cmd("/usr/bin/kitty --class spoff --title Spoff -o window_padding_width=0 -o placement_strategy=top-left " .. home .. "/.local/bin/spoff"), { description = "Launch Spoff" })
hl.unbind("SUPER + SHIFT + CTRL + H")
hl.unbind("SUPER + SHIFT + CTRL + J")
hl.unbind("SUPER + SHIFT + CTRL + K")
hl.unbind("SUPER + SHIFT + CTRL + L")
hl.unbind("SUPER + SHIFT + CTRL + down")
hl.unbind("SUPER + SHIFT + CTRL + left")
hl.unbind("SUPER + SHIFT + CTRL + right")
hl.unbind("SUPER + SHIFT + CTRL + up")
hl.unbind("SUPER + SHIFT + F")
hl.unbind("SUPER + SHIFT + H")
hl.unbind("SUPER + SHIFT + I")
hl.unbind("SUPER + SHIFT + J")
hl.unbind("SUPER + SHIFT + K")
hl.unbind("SUPER + SHIFT + L")
hl.unbind("SUPER + SHIFT + N")
hl.unbind("SUPER + SHIFT + Page_Down")
hl.unbind("SUPER + SHIFT + Page_Up")
hl.unbind("SUPER + SHIFT + U")
hl.unbind("SUPER + SHIFT + mouse_down")
hl.unbind("SUPER + SHIFT + mouse_up")
hl.unbind("SUPER + SHIFT + down")
hl.unbind("SUPER + SHIFT + left")
hl.unbind("SUPER + SHIFT + right")
hl.unbind("SUPER + SHIFT + up")
hl.unbind("SUPER + T")
hl.unbind("SUPER + U")
hl.unbind("SUPER + V")
hl.unbind("SUPER + mouse_down")
hl.unbind("SUPER + mouse_up")
hl.unbind("SUPER + Y")
hl.unbind("SUPER + Z")
hl.bind("SUPER + Z", hl.dsp.window.float({ action = "toggle" }), { description = "Toggle Floating Window" })
hl.unbind("SUPER + code:20")
hl.unbind("SUPER + code:21")
hl.unbind("SUPER + comma")
hl.unbind("SUPER + space")

-- === Global PC-wide Media Controls (playerctl) ===
hl.unbind("XF86AudioPlay")
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true, description = "Play/Pause" })
hl.unbind("XF86AudioPause")
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true, description = "Play/Pause" })
hl.unbind("XF86AudioPrev")
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true, description = "Previous Track" })
hl.unbind("XF86AudioNext")
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true, description = "Next Track" })

-- Keep plain F7, F8, F9 unbound so playback controls only trigger with Fn (XF86Audio keys)
hl.unbind("F7")
hl.unbind("F8")
hl.unbind("F9")

-- Crosshair Screen Overlay Toggle
hl.unbind("SUPER + SHIFT + X")
hl.bind("SUPER + SHIFT + X", hl.dsp.exec_cmd(home .. "/.local/bin/crosshair toggle"), { description = "Toggle Screen Crosshair" })
