-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "desc:Samsung Electric Company LF22T35 HK7X500372", mode = "1920x1080@74.970", position = "1920x0", scale = 1, bitdepth = 10 })
hl.monitor({ output = "", mode = "preferred", position = "0x0", scale = 1 })
hl.monitor({ output = "desc:BOE 0x0C29 0x00000067", mode = "1920x1080@144.002", position = "0x0", scale = 1, vrr = 0, bitdepth = 10 })
hl.monitor({ output = "desc:Dell Inc. DELL P2425HE 6C84N84", mode = "1920x1080@100.000", position = "1920x0", scale = 1, vrr = 1, bitdepth = 10, cm = "dp3" })
